### ISSUE TITLE
[JC] (SBT) Add column active to citations entity

### ISSUE THREAD

**Issue by felipelvira** [AllianceBioversityCIAT/onecgiar-submission-tool#59]
A Boolean column that controls inactivity of the citation should be add.

- [x] Add column called **active** to entity **citations** .

**Deliverable:**
A filter over the citations created / updated. Only active citations should be displayed in the submission tool.

**Comment by JuankCadavid** [comment]
I added a new migration called 1627437625304-AlterTableCitationsAddColumnActive and modified the endpoint for addlink and getlink including the new active field.
